### ISSUE TITLE
The documentation mentions `ADMIN_USER_IDS` which is not an existing setting

### ISSUE THREAD

**Issue by FroutSarain** [bokoboshahni/eve-indy-watch#147]
`ADMIN_USER_IDS` is present in both `lib/tasks/bootstrap.rake` and `DEVELOPMENT.md`, but not in the code.

Is it supposed to be `ADMIN_CHARACTER_IDS` instead ?

**Comment by bokoboshahni** [comment]
Good catch, it should be `ADMIN_CHARACTER_IDS`.
